FROM nginx:stable

COPY index.html /usr/share/nginx/html/index.html 
COPY bootstrap.min.css /usr/share/nginx/html/bootstrap.min.css
COPY bootstrap.min.js /usr/share/nginx/html/bootstrap.min.js

COPY . /usr/share/nginx/html/

EXPOSE 80